setup for Xylon

diff --git a/releasetools/squisher b/releasetools/squisher
--- a/releasetools/squisher
+++ b/releasetools/squisher
@@ -1,8 +1,11 @@
 #!/bin/sh
 #
 # Squish a CM otapackage for distribution
-# cyanogen
 #
+# cyanogen
+# AOSP - XYLON
+
+. $ANDROID_BUILD_TOP/vendor/aosp/tools/colors
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -35,12 +38,42 @@ if [ ! -f "$OTAPACKAGE" ]; then
 	exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/device/bn/acclaim/releasetools/opticharger
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/aosp/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
+
+# Some products want a squashfs for xbin for space
+case "$TARGET_PRODUCT" in
+	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+	*) WANT_SQUASHFS=0 ;;
+esac
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+	fatal=0
+	MKSQUASHFS_VER_REQ=4
+	if type mksquashfs >/dev/null 2>&1; then
+		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+			echo
+			echo $CL_RED"ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."$CL_RST
+			fatal=1
+		fi
+	else
+		echo
+		echo $CL_RED"ERROR: $TARGET_PRODUCT requires mksquashfs."$CL_RST
+		fatal=1
+	fi
+
+	if [ "$fatal" -ne 0 ]; then
+		echo
+		echo $CL_YLW"       Unoptimized package is still available at"
+		echo "         $OTAPACKAGE"$CL_RST
+		exit $fatal
+	fi
+fi
+
 REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
+echo $CL_CYN"Sanitizing environment..."$CL_RST
 rm -rf $REPACK
 mkdir -p $REPACK
 echo
@@ -50,20 +83,68 @@ echo
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
+echo $CL_CYN"Unpacking $OTAPACKAGE..."$CL_RST
 unzip $QUIET $OTAPACKAGE
 echo
-cd $REPACK/ota/system/framework
-$OPTICHARGER framework-res.apk
-cd $REPACK/ota/system/app
+
+# Move all apks to the same directory so xargs can
+# use also with framework-res.apk. This allow process
+# framework-res.apk in parallel with other apks
+mkdir -p $REPACK/parallel
+cd $REPACK/parallel
+cp $REPACK/ota/system/framework/framework-res.apk .
+cp $REPACK/ota/system/app/*.apk .
+
+# Do optimization in parallel
 find ./ -name \*.apk | $XARGS $OPTICHARGER
+
+# Move optimized apks to repack directory
+mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
+
+# Return to directory
+cd $REPACK/ota
+rm -rf $REPACK/parallel
 )
 
-rm $REPACK/ota/system/app/MagicSmokeWallpapers.apk
 rm $REPACK/ota/system/app/Bluetooth.apk
+rm $REPACK/ota/system/app/DSPManager.apk
+rm $REPACK/ota/system/app/MagicSmokeWallpapers.apk
+rm $REPACK/ota/system/app/Torch.apk
+rm $REPACK/ota/system/app/Launcher2.apk
+
 
 #mv $REPACK/ota/system/app/Phone.apk $REPACK/ota/system/app/Phone.apk.bak
 #mv $REPACK/ota/system/app/TelephonyProvider.apk $REPACK/ota/system/app/TelephonyProvider.apk.bak
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+	squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
+	updater=$REPACK/ota/META-INF/com/google/android/updater-script
+
+	# Relocate su
+	cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
+	rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
+	mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
+	chmod -R 555 $REPACK/_xbin/*
+
+	# Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
+	# Forgive me for the regex hell here.
+	ln -s ../bin/su $REPACK/_xbin/su
+	for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
+	do
+		ln -s busybox $REPACK/_xbin/$link
+	done
+
+	# Create the squashfs with new and improved symlinkage!
+	mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
+	rm -rf $REPACK/ota/system/xbin/*
+	mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
+	chmod 444 $REPACK/ota/system/xbin/xbin.sqf
+
+	# Remove xbin stuff and fix up updater-script
+	$SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
+fi
+
 
 # Fix build.prop
 $SED -i \
@@ -71,22 +152,12 @@ $SED -i \
 	-e '/ro\.build\.type/s/eng/user/' \
 	$REPACK/ota/system/build.prop
 
-# Delete ParanoidAndroid specific files
-if [ -f $ANDROID_BUILD_TOP/vendor/pa/tools/squisher.rm ]; then
-	for RM_FILE in `cat $ANDROID_BUILD_TOP/vendor/pa/tools/squisher.rm`; do
-		rm -f $REPACK/ota/$RM_FILE
-	done
-fi
-
-# Delete target product specific files
-if [ -f $ANDROID_BUILD_TOP/vendor/pa/tools/$TARGET_PRODUCT-squisher.rm ]; then
-	for RM_FILE in `cat $ANDROID_BUILD_TOP/vendor/pa/tools/$TARGET_PRODUCT-squisher.rm`; do
-		rm -f $REPACK/ota/$RM_FILE
-	done
-fi
 
 # Delete unnecessary binaries
 ( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
+
+# Delete leftover wireless driver
+# rm -rf $REPACK/ota/system/lib/modules/*/kernel/drivers/net
 
 # No need for recovery
 rm -rf $REPACK/ota/recovery
@@ -96,36 +167,24 @@ rm -rf $REPACK/ota/recovery
 	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
 # Determine what to name the new signed package
-if [ -z "$CYANOGEN_NIGHTLY" ]; then
-	PAVERSION=`grep 'ro.modversion=' $REPACK/ota/system/build.prop | sed -e 's/ro.modversion=//g'`
-	OVERLAYTARGET=`grep 'ro.pa.family=' $REPACK/ota/system/build.prop | sed -e 's/ro.pa.family=//g'`
-	: ${PAVERSION:=nightly}
-	OUTFILE=$OUT/$PAVERSION.zip
-	echo PAVERSION: $PAVERSION
-else
-	OUTFILE=$OUT/update-squished.zip
-fi
 
-# Copy ParanoidPreferences overlays
-printf "Copying overlay preferences for $OVERLAYTARGET..."
-echo
-mkdir $REPACK/ota/system/etc/paranoid/preferences
-mkdir $REPACK/ota/system/etc/paranoid/preferences/images
-cp -r $ANDROID_BUILD_TOP/vendor/pa/prebuilt/preferences/images/* $REPACK/ota/system/etc/paranoid/preferences/images/
-cp -r $ANDROID_BUILD_TOP/vendor/pa/prebuilt/preferences/$OVERLAYTARGET/* $REPACK/ota/system/etc/paranoid/preferences/
+#MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
+VERSION=`sed -n -e'/ro.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
+MODVERSION="$VERSION"
+OUTFILE=$OUT/$MODVERSION.zip
 
 # Pack it up and sign
-printf "Zipping package..."
+echo $CL_CYN"Zipping package..."$CL_RST
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
 echo
-printf "Signing package..."
+echo $CL_CYN"Signing package..."$CL_RST
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
 java -Xmx1024m \
 	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
 	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
 	$REPACK/update.zip $OUTFILE
 echo
-printf "Cleaning up..."
+echo $CL_CYN"Cleaning up..."$CL_RST
 rm -rf $REPACK
 echo
 
@@ -135,8 +194,10 @@ img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
 echo
-echo "Package complete: $OUTFILE"
-cat $img.md5sum
+echo  $CL_CYN"=========== -=XYE=- Package complete-==========="$CL_RST
+echo $CL_GRN"ROM Directory:"$CL_CYN" $OUTFILE"$CL_RST
+echo $CL_GRN"md5:"$CL_CYN" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
+echo  $CL_CYN"===========    GO ADB PUSH IT NAO!   ==========="$CL_RST
 echo
 )
 
